CREATE DATABASE ticketpayment

USE ticketpayment

CREATE TABLE IF NOT EXISTS TicketOrders (
	OrderId BIGINT PRIMARY KEY AUTO_INCREMENT,
	BankAccount BIGINT UNIQUE NOT NULL,
	Amount DECIMAL(15,2) NOT NULL)
;

CREATE TABLE IF NOT EXISTS Customers (
	CustomerId BIGINT PRIMARY KEY AUTO_INCREMENT,
	FirstName VARCHAR(25) NOT NULL,
	LastName VARCHAR(25) NOT NULL,
	Country VARCHAR(25) NOT NULL,
	OrderId BIGINT,
	FOREIGN KEY (OrderId) REFERENCES TicketOrders (OrderId))
;
