server:
  port: 8888
#  timeZone: UTC
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Artemiy7/config-repo
          clone-on-start: true
          search-paths: {application}
          default-label: master

#logging.level.org.springframework.cloud=debug
#logging.level.org.springframework.web=debug
