#server:
#  port: 8080
#  error:
#    whitelabel:
#      enabled: false
#spring:
#  db:
#    driver: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/ticketpayment?serverTimezone=UTC
#    username: root
#    password: aaaa
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#        show_sql: true
#        hbm2ddl:
#          auto: none
#        packagesToScan: net.ticket
#  mvc:
#    throw-exception-if-no-handler-found: true
#  resources:
#    add-mappings: false
#
#service:
#  default-currency: usd
#  bank:
#    account:
#      uri: http://localhost:8082/bank/account/%s
#    payment:
#      uri: http://localhost:8082/bank/payment
#  occasion-coefficient:
#    concert:
#      club:
#        balcony: 7.0
#        vip: 2.0
#        fan: 4.0
#        date: 0.3
#        seat: 0.3
#      stadion:
#        vip: 3.0
#        fan: 1.0
#        seating: 2.0
#        date: 0.2
#        seat: 0.1
#    train:
#      intercity:
#        business: 2.0
#        economic: 1.0
#        date: 0.1
#        seat: 0.7
#
#exchange:
#  uri: http://localhost:8081/exchange/%s/%s/%s
#pdfgenerator:
#  uri: http://localhost:8083/generateTicketPDF